const employees = [
  {
    employeeId: 1,
    name: "CEO",
    phoneNumber: "123-456-7890",
    email: "ceo@example.com",
    levelCode: "L1",
    managerId: null,
  },
  {
    employeeId: 2,
    name: "VP of Operations",
    phoneNumber: "234-567-8901",
    email: "vp_operations@example.com",
    levelCode: "L2",
    managerId: 1,
  },
  {
    employeeId: 3,
    name: "Regional Manager",
    phoneNumber: "345-678-9012",
    email: "regional_manager@example.com",
    levelCode: "L3",
    managerId: 2,
  },
  {
    employeeId: 4,
    name: "Store Manager",
    phoneNumber: "456-789-0123",
    email: "store_manager@example.com",
    levelCode: "L4",
    managerId: 2,
  },
  {
    employeeId: 5,
    name: "Assistant Store Manager",
    phoneNumber: "567-890-1234",
    email: "assistant_manager@example.com",
    levelCode: "L4",
    managerId: 2,
  },
  {
    employeeId: 6,
    name: "Sales Associate",
    phoneNumber: "678-901-2345",
    email: "sales_associate@example.com",
    levelCode: "L4",
    managerId: 2,
  },
  {
    employeeId: 7,
    name: "VP of Finance",
    phoneNumber: "123-456-7890",
    email: "ceo@example.com",
    levelCode: "L2",
    managerId: 1,
  },
  {
    employeeId: 8,
    name: "Accountant",
    phoneNumber: "123-456-7890",
    email: "ac@example.com",
    levelCode: "L3",
    managerId: 7,
  },
  {
    employeeId: 9,
    name: "Junior Sales Associate",
    phoneNumber: "678-901-2345",
    email: "sales_associateJunior@example.com",
    levelCode: "L%",
    managerId: 6,
  },
];
